# Generated by Django 2.0.3 on 2019-10-16 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191016_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantaty',
            new_name='quantity',
        ),
    ]
